# Generated by Django 4.0.3 on 2022-04-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_deliverable', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tag')),
            ],
        ),
    ]
