# Generated by Django 4.0.3 on 2022-04-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_foodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='FoodImage',
        ),
    ]
